language: ruby
rvm:
  - "2.0.0"
before_script:
  - psql -c 'create database portfolio_test;' -U postgres
env:
  - DB=postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
bundler_args: --binstubs=./bundler_stubs
